import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Services from "./(pages)/services/page";
import About from "./(pages)/about/page";
import Contact from "./(pages)/contact/page";
import Footer from "./components/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Services/>
        <About/>
        <Contact/>
        <Footer/>
      </body>
      
    </html>
  );
}
